"""50 Client Templates — Uplyncio guest posting AGENCY pitch.
Pain points + punch lines. Positions Uplyncio as a professional guest posting agency.
90-130 words, "Hi there," start, first-name sign, subject uses {{website}} (full domain),
body uses {{company_name}} (clean name). SEO/link-building focused.
"""

COMPANY_FOOTER = """
<div style="margin-top:24px;font-family:Arial,sans-serif">
<div style="text-align:center;margin-bottom:12px">
<a href="{{unsubscribe_url}}" style="color:#6b7280;font-size:11px;text-decoration:underline">Unsubscribe</a>
</div>
<div style="padding-top:10px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af">
<b style="color:#1a1a2e;font-size:12px">Uplyncio.com</b><br>
<span style="color:#9ca3af">Guest Posting & Niche Edit Platform</span><br>
<a href="mailto:info@uplyncio.com" style="color:#4f46e5;text-decoration:none;font-size:11px">info@uplyncio.com</a>
</div></div>"""

TEMPLATES = [
    {"subject": 'Guest posts that actually rank {{website}}',
     "body": "Hi there,\n\nIf {{company_name}} is publishing great content but still not ranking, the problem usually isn't your content — it's your backlinks.\n\nWe're Uplyncio, a guest posting agency that helps brands earn quality backlinks from high-authority sites in their niche. Real placements, real traffic, real ranking improvements — no link farms, no shortcuts.\n\nHere's what we handle for you:\n- Finding relevant, high-DA sites\n- Writing the article\n- Securing the placement with a dofollow link to {{website}}\n\nMost clients see movement within 60-90 days. If you're ready to stop competing on content alone and start winning on authority, let's talk.\n\nWant a few sites where {{company_name}} could get featured?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Is {{website}} stuck on page 2?',
     "body": "Hi there,\n\nBe honest — is {{company_name}} stuck on page 2 of Google while competitors sit above you? Nine times out of ten, the difference is backlinks.\n\nWe're Uplyncio, a guest posting agency. We get brands like yours published on trusted, high-authority sites with natural backlinks that push your rankings up. Everything is white-hat and fully managed — we research, write, and place, you just approve.\n\nThe result: more organic traffic, stronger domain authority, and pages that finally rank where they should.\n\nWe've done this for hundreds of businesses, and {{company_name}} looks like a perfect fit.\n\nWant to see a few high-DA sites we could get you featured on?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Backlinks {{website}} deserves',
     "body": "Hi there,\n\n{{company_name}} deserves better backlinks — the kind Google actually rewards.\n\nWe're Uplyncio, a guest posting agency that specialises in earning authority links through editorial placements on real, niche-relevant sites. No spam, no private blog networks, no risk to your site — just quality guest posts that build lasting SEO value.\n\nWe handle the entire process: site research, content writing, outreach, and publishing, each with a natural dofollow link to {{website}}.\n\nGreat content only takes you so far. Authority backlinks are what get you to page one and keep you there.\n\nCan I send over a shortlist of sites where {{company_name}} would be a strong fit?\n\nBest,\n{{sender_name}}"},
    {"subject": "Grow {{website}}'s traffic — the right way",
     "body": "Hi there,\n\nEvery business wants more organic traffic — but few realise it comes down to one thing Google trusts above almost everything else: authority backlinks.\n\nWe're Uplyncio, a guest posting agency. We help brands like {{company_name}} grow traffic the right way, through quality guest posts on high-authority sites in your niche. Each placement earns you a natural backlink that improves rankings and drives relevant visitors to {{website}}.\n\nNo shortcuts, no risk — everything is white-hat and fully managed on our end. You approve, we deliver.\n\nIf you're serious about ranking higher and want a partner who does it properly, we should talk.\n\nWant a few example sites for {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": '{{website}}, meet high-authority backlinks',
     "body": "Hi there,\n\nYou can have the best product in your market, but if {{company_name}} doesn't have the backlinks to back it up, Google won't put you at the top.\n\nWe're Uplyncio, a guest posting agency that fixes exactly that. We get brands featured on high-authority sites with natural, dofollow backlinks — the kind that genuinely move rankings and build domain authority.\n\nWe do all the heavy lifting: finding the right sites, writing the content, and securing placements that link back to {{website}}.\n\nOur clients don't buy random links. They invest in real authority that compounds over time.\n\nWant to see which high-DA sites {{company_name}} could get featured on?\n\nBest,\n{{sender_name}}"},
    {"subject": 'SEO that moves {{website}} up Google',
     "body": "Hi there,\n\nSEO can feel like a black box — you publish, you wait, and nothing moves. Usually the missing piece is authority, and authority comes from backlinks.\n\nWe're Uplyncio, a guest posting agency. We help {{company_name}} climb Google through quality guest posts on trusted sites in your niche, each with a dofollow link to {{website}}. White-hat, fully managed, and built for long-term results.\n\nNo guesswork, no risky tactics — just proven link building that steadily improves your rankings and organic traffic.\n\nMany of our clients see real movement within 60-90 days.\n\nIf you'd like to stop guessing and start ranking, I'd be glad to share a few sites we could get {{company_name}} featured on.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Quality links for {{website}}',
     "body": "Hi there,\n\nNot all backlinks are equal. One link from a trusted, high-authority site can outperform a hundred cheap ones — and it won't put {{company_name}} at risk.\n\nWe're Uplyncio, a guest posting agency that earns you exactly those links. Through editorial guest posts on real, niche-relevant sites, we help you build the kind of authority Google rewards with better rankings.\n\nWe manage everything: research, writing, outreach, and publishing, each with a natural link back to {{website}}.\n\nQuality over quantity is the only link building strategy that lasts — and it's the only kind we do.\n\nWant to see a few high-DA sites where {{company_name}} could be featured?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Your competitors are outranking {{website}}',
     "body": "Hi there,\n\nHere's an uncomfortable truth: your competitors are probably outranking {{company_name}} not because they're better, but because they have stronger backlinks.\n\nWe're Uplyncio, a guest posting agency that levels the playing field. We get brands featured on high-authority sites with quality backlinks that boost rankings and drive organic traffic to {{website}}.\n\nEverything is white-hat and done for you — we find the sites, write the content, and secure the placements. You just approve.\n\nWhile your competitors keep building authority, every month you wait is ground you give up.\n\nWant to see how we could close that gap for {{company_name}}? I can share a few target sites.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Featured articles for {{website}}',
     "body": "Hi there,\n\nImagine {{company_name}} featured in expert articles on the most trusted sites in your niche — the ones your customers already read.\n\nWe're Uplyncio, a guest posting agency that makes that happen. We write high-quality articles, place them on high-authority sites, and secure natural dofollow links to {{website}} that build your rankings and reputation at the same time.\n\nIt's editorial content, not ads — so it earns trust in a way advertising never can. And it's fully managed, so it takes nothing off your plate.\n\nMore visibility, more authority, more organic traffic. That's what quality guest posting delivers.\n\nWant a shortlist of sites {{company_name}} could be featured on?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Link building done right for {{website}}',
     "body": "Hi there,\n\nLink building has a bad reputation — and honestly, most of it is deserved. Spammy links, private blog networks, cheap directories: they do more harm than good.\n\nWe're Uplyncio, a guest posting agency that does link building the right way. We earn {{company_name}} real backlinks through editorial guest posts on trusted, high-authority sites, each with a natural dofollow link to {{website}}.\n\nNo risk to your site, no shortcuts, no penalties — just quality placements that build authority and improve rankings over time.\n\nWe handle the whole process so you don't have to lift a finger.\n\nIf you want link building that actually works, let's talk. Can I share a few target sites for {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Get {{website}} the authority it needs',
     "body": "Hi there,\n\nGreat content deserves to be seen — but without authority, even the best content sits buried on page 2.\n\nWe're Uplyncio, a guest posting agency. We give {{company_name}} the authority it needs by earning quality backlinks from high-DA sites in your niche. Each guest post is professionally written and placed on a real, trusted site, with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for lasting results — no guesswork, no risk.\n\nAuthority is what separates the sites on page 1 from everyone else. We help you build it, properly.\n\nWant to see which sites {{company_name}} could get featured on?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Rankings boost for {{website}}',
     "body": "Hi there,\n\nIf {{company_name}}'s rankings have plateaued, you've probably maxed out what content alone can do. The next lever is authority — and that means backlinks.\n\nWe're Uplyncio, a guest posting agency that helps brands break through exactly this plateau. We earn you quality backlinks through editorial guest posts on high-authority, niche-relevant sites, each linking back to {{website}}.\n\nEverything is white-hat and fully managed. We find the sites, write the content, and secure the placements — you simply approve and watch your rankings climb.\n\nMost clients see movement within 60-90 days.\n\nReady to get {{company_name}} moving again? I can share a few high-DA target sites.\n\nBest regards,\n{{sender_name}}"},
    {"subject": '{{website}} deserves better backlinks',
     "body": "Hi there,\n\n{{company_name}} deserves backlinks that build your brand, not put it at risk.\n\nWe're Uplyncio, a guest posting agency focused on quality over everything. We earn you links through editorial guest posts on trusted, high-authority sites in your niche — the kind of placements Google rewards with better rankings and lasting authority.\n\nNo link farms, no PBNs, no cheap tricks. Just real content on real sites with a natural dofollow link to {{website}}.\n\nWe manage the whole process end to end, so it takes nothing off your plate.\n\nIf you're ready for backlinks you can actually trust, let's talk. Want a few example sites for {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Traffic + rankings for {{website}}',
     "body": "Hi there,\n\nTraffic and rankings don't come from luck — they come from authority. And nothing builds authority faster than quality backlinks from trusted sites.\n\nWe're Uplyncio, a guest posting agency. We help {{company_name}} earn exactly those links through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for long-term growth. We handle site research, writing, and placement — you approve, we deliver, your rankings climb.\n\nOur clients don't chase quick wins. They build authority that compounds month after month.\n\nWant to see a few sites where {{company_name}} could get featured?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest posting for {{website}} that works',
     "body": "Hi there,\n\nMost guest posting is a waste of money — cheap sites, no traffic, links that do nothing. Done right, though, it's one of the most powerful SEO tools there is.\n\nWe're Uplyncio, a guest posting agency that does it right. We get {{company_name}} featured on high-authority, niche-relevant sites with natural dofollow links to {{website}} that genuinely improve rankings and drive traffic.\n\nEvery placement is on a real site with real readers. We handle research, writing, and outreach — you just approve.\n\nQuality guest posting isn't cheap, but it works. And it keeps working long after you've paid for it.\n\nWant to see which high-DA sites would fit {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'More organic traffic for {{website}}',
     "body": "Hi there,\n\nEvery month {{company_name}} isn't building authority is a month your competitors pull further ahead in search results.\n\nWe're Uplyncio, a guest posting agency that helps you catch up and stay ahead. We earn quality backlinks through editorial guest posts on high-authority sites in your niche, driving more organic traffic to {{website}}.\n\nWhite-hat, fully managed, and proven. We find the sites, write the content, and secure the placements with natural dofollow links — you simply approve.\n\nSEO rewards consistency and authority. We deliver both, month after month.\n\nIf you're ready to grow {{company_name}}'s traffic properly, I'd love to share a few target sites. Interested?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Authority backlinks for {{website}}',
     "body": "Hi there,\n\nOne authority backlink from a trusted site can do more for {{company_name}} than months of on-page tweaks.\n\nWe're Uplyncio, a guest posting agency. We earn brands like yours quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nNo spam, no risk, no shortcuts — just real placements on real sites that build authority and improve rankings. And it's fully managed, so it takes nothing off your plate.\n\nIf your on-page SEO is solid but rankings still won't budge, backlinks are almost always the missing piece.\n\nWant to see a few high-DA sites where {{company_name}} could be featured?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest posts on real sites — {{website}}',
     "body": "Hi there,\n\nAnyone can promise backlinks. Very few can get you featured on real, high-authority sites with actual traffic — the only links that truly move rankings.\n\nWe're Uplyncio, a guest posting agency that delivers exactly that. We place {{company_name}} on trusted, niche-relevant sites through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built to last. We handle the research, writing, and outreach — you just approve the final piece.\n\nReal sites, real authority, real ranking improvements. That's the difference between guest posting that works and guest posting that wastes your budget.\n\nWant a shortlist of sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": '{{website}} on high-DA publications',
     "body": "Hi there,\n\nGetting {{company_name}} onto high-DA publications isn't about luck or connections — it's about knowing how to earn those placements. That's what we do.\n\nWe're Uplyncio, a guest posting agency. We get brands featured on high-authority sites in their niche through editorial guest posts, each with a natural dofollow link to {{website}} that boosts your rankings and authority.\n\nEverything is white-hat and fully managed. We find the right sites, write compelling content, and secure the placements — you simply approve.\n\nHigh-DA backlinks are some of the most valuable assets in SEO. We help you build them, the right way.\n\nWant to see which publications {{company_name}} could get featured on?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'SEO growth partner for {{website}}',
     "body": "Hi there,\n\nIf SEO feels like throwing effort into a void, you're not alone — and it usually means one thing is missing: authority backlinks.\n\nWe're Uplyncio, a guest posting agency that becomes your SEO growth partner. We earn {{company_name}} quality backlinks through editorial guest posts on high-authority, niche-relevant sites, each linking to {{website}}.\n\nWhite-hat, fully managed, and built for steady, compounding results. We handle everything — you approve and watch your rankings and traffic grow.\n\nWe don't do quick fixes. We build the kind of authority that keeps paying off month after month.\n\nWant to see how we'd approach {{company_name}}'s growth? I can share a few target sites.\n\nBest,\n{{sender_name}}"},
    {"subject": "Stop guessing with {{website}}'s SEO",
     "body": "Hi there,\n\nTired of guessing what will finally move {{company_name}} up Google? The answer is almost always the same: quality backlinks from trusted sites.\n\nWe're Uplyncio, a guest posting agency that takes the guesswork out of SEO. We earn you authority links through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, proven. We find the sites, write the content, and secure the placements — you just approve.\n\nStop experimenting with tactics that don't move the needle. Authority backlinks are what actually rank sites, and we build them properly.\n\nWant a few example sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Backlinks that Google rewards — {{website}}',
     "body": "Hi there,\n\nGoogle rewards trust — and nothing signals trust like backlinks from established, high-authority sites.\n\nWe're Uplyncio, a guest posting agency. We earn {{company_name}} exactly those backlinks through editorial guest posts on trusted, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nNo PBNs, no cheap directories, no risk — just real content on real sites that builds lasting authority and improves your rankings.\n\nWe handle site research, writing, outreach, and publishing, so it takes nothing off your plate.\n\nIf you want backlinks that Google genuinely rewards, we should talk. Can I send over a shortlist of high-DA sites for {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest posting agency for {{website}}',
     "body": "Hi there,\n\nMost businesses know they need backlinks. Few know how to get quality ones without risking a penalty. That's where an agency that does this every day makes all the difference.\n\nWe're Uplyncio, a guest posting agency. We earn {{company_name}} authority backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for lasting results. We handle everything — you just approve.\n\nDIY link building is slow and risky. A specialist agency gets you real results, faster and safer.\n\nWant to see which sites {{company_name}} could get featured on?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Link building for {{website}}',
     "body": "Hi there,\n\nSolid rankings come down to one thing more than any other: quality backlinks. And building them is exactly what we do, every single day.\n\nWe're Uplyncio, a guest posting agency. We get {{company_name}} featured on high-authority, niche-relevant sites through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nEverything is white-hat and fully managed. We research the sites, write the content, and secure the placements — you simply approve and watch your authority grow.\n\nWe don't sell random links. We build real authority that improves rankings and drives organic traffic over the long term.\n\nWant a few high-DA target sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Rank {{website}} higher on Google',
     "body": "Hi there,\n\nYou've optimised your site, published great content, done everything right — and {{company_name}} still won't rank. The missing piece is almost always authority.\n\nWe're Uplyncio, a guest posting agency that supplies exactly that. We earn you quality backlinks through editorial guest posts on trusted, high-DA sites in your niche, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, proven. We handle the research, writing, and outreach — you just approve.\n\nOn-page SEO gets you ready to rank. Backlinks are what actually get you there.\n\nReady to rank {{company_name}} higher? I can share a few target sites to get started.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Content + backlinks for {{website}}',
     "body": "Hi there,\n\nContent gets you in the game. Backlinks win it. If {{company_name}} is producing quality content but not seeing results, this is almost certainly why.\n\nWe're Uplyncio, a guest posting agency. We pair your content strategy with quality backlinks from high-authority sites, earned through editorial guest posts that link naturally to {{website}}.\n\nWhite-hat, fully managed, and built for long-term growth. We find the sites, write the articles, and secure the placements — you approve, we deliver.\n\nContent plus authority is the combination that actually ranks sites. We handle the authority side, properly.\n\nWant to see a few high-DA sites where {{company_name}} could be featured?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Get {{website}} noticed',
     "body": "Hi there,\n\nThe best product in your market means nothing if customers can't find {{company_name}} on Google. Visibility comes from authority — and authority comes from backlinks.\n\nWe're Uplyncio, a guest posting agency that gets your brand noticed. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We do the research, writing, and outreach — you just approve.\n\nMore authority means higher rankings, which means more of the right people finding {{company_name}}.\n\nWant to see which sites could get you featured? I'd be glad to share a shortlist.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Quality guest posts for {{website}}',
     "body": "Hi there,\n\nThere's a big difference between guest posts that build authority and guest posts that waste your money. The site quality is everything.\n\nWe're Uplyncio, a guest posting agency that only works with real, high-authority sites. We get {{company_name}} featured through editorial guest posts, each with a natural dofollow link to {{website}} that genuinely improves rankings.\n\nNo low-quality sites, no spam, no risk. Every placement is on a trusted, niche-relevant site with real traffic. And it's fully managed, so it takes nothing off your plate.\n\nQuality guest posts are an investment that keeps paying off. We make sure yours are the right kind.\n\nWant to see a few sites for {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": "{{website}}'s SEO growth plan",
     "body": "Hi there,\n\nSEO isn't magic — it's a plan. And for most businesses, the highest-impact part of that plan is building quality backlinks.\n\nWe're Uplyncio, a guest posting agency that builds {{company_name}}'s SEO growth plan around exactly that. We earn you authority links through editorial guest posts on high-DA, niche-relevant sites, each linking to {{website}}.\n\nWhite-hat, fully managed, and built for steady results. We handle everything — you approve and watch your rankings improve.\n\nNo hype, no shortcuts. Just a clear, proven approach to growing your authority and organic traffic.\n\nWant to see how we'd build {{company_name}}'s backlink strategy? I can share a few target sites.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Authority links {{website}} can trust',
     "body": "Hi there,\n\nCheap backlinks can tank your rankings. Quality backlinks from trusted sites are the ones {{company_name}} can actually rely on.\n\nWe're Uplyncio, a guest posting agency that delivers only the second kind. We earn you authority links through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nNo PBNs, no spam, no risk of penalties — just real placements on real sites that build lasting authority. And it's fully managed, so you don't lift a finger.\n\nIf you want backlinks you can trust to help, not hurt, we should talk.\n\nWant a shortlist of high-DA sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Guest posts for {{website}} — done for you',
     "body": "Hi there,\n\nBuilding quality backlinks is time-consuming, technical, and easy to get wrong. So let us handle it for you.\n\nWe're Uplyncio, a guest posting agency. We earn {{company_name}} authority backlinks through editorial guest posts on high-DA, niche-relevant sites — completely done for you. We find the sites, write the content, and secure the placements, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for lasting results. All you do is approve.\n\nYour time is better spent running your business. We'll handle the link building that ranks it higher.\n\nWant to see which sites {{company_name}} could get featured on?\n\nThanks,\n{{sender_name}}"},
    {"subject": "Boost {{website}}'s domain authority",
     "body": "Hi there,\n\nDomain authority is the single best predictor of how well {{company_name}} will rank — and the fastest way to build it is quality backlinks.\n\nWe're Uplyncio, a guest posting agency. We boost your domain authority through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle research, writing, and outreach — you just approve.\n\nHigher domain authority means better rankings across every page on your site, not just one. It's one of the smartest long-term SEO investments you can make.\n\nWant to see a few sites we could get {{company_name}} featured on?\n\nBest,\n{{sender_name}}"},
    {"subject": 'SEO backlinks for {{website}}',
     "body": "Hi there,\n\nSEO backlinks aren't all created equal. The ones that actually rank {{company_name}} come from real, trusted, high-authority sites — and those are exactly the ones we earn.\n\nWe're Uplyncio, a guest posting agency. We get you featured through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nNo spam, no risk, no shortcuts — just quality placements that build authority and improve rankings over time. Fully managed, so it takes nothing off your plate.\n\nIf you want SEO backlinks that genuinely move the needle, we should talk.\n\nWant to see a few high-DA sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": '{{website}} on trusted industry sites',
     "body": "Hi there,\n\nGetting {{company_name}} featured on trusted industry sites does two things at once: it builds your authority and puts your brand in front of the right audience.\n\nWe're Uplyncio, a guest posting agency that makes both happen. We place you on high-DA, niche-relevant sites through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you just approve.\n\nOne quality placement builds rankings and reputation simultaneously. That's the power of guest posting done properly.\n\nWant to see which trusted sites {{company_name}} could get featured on?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Grow {{website}} with guest posting',
     "body": "Hi there,\n\nGrowing {{company_name}} through guest posting isn't about volume — it's about getting the right placements on the right sites.\n\nWe're Uplyncio, a guest posting agency that focuses on exactly that. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}} that drives rankings and organic traffic.\n\nWhite-hat, fully managed, and built for lasting results. We do the research, writing, and outreach — you simply approve.\n\nA handful of quality placements will do more for your growth than a hundred cheap ones. We make sure you get the right kind.\n\nWant a shortlist of sites for {{company_name}}?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Real backlinks for {{website}}',
     "body": "Hi there,\n\nReal backlinks come from real sites with real traffic. Everything else is just noise — and often a risk to {{company_name}}.\n\nWe're Uplyncio, a guest posting agency that deals only in the real thing. We earn you authority backlinks through editorial guest posts on trusted, high-DA sites in your niche, each with a natural dofollow link to {{website}}.\n\nNo PBNs, no spam, no penalties — just genuine placements that build authority and improve rankings. And it's fully managed, so you don't lift a finger.\n\nIf you're done wasting budget on links that do nothing, let's talk.\n\nWant to see a few real, high-DA sites for {{company_name}}?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Guest posting partner for {{website}}',
     "body": "Hi there,\n\nThe right guest posting partner doesn't just build links — they build your authority, your rankings, and your reputation, all at once.\n\nWe're Uplyncio, a guest posting agency built to be exactly that partner for {{company_name}}. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for the long term. We handle everything — you just approve.\n\nWe're not a one-off vendor. We're a growth partner focused on results that compound over time.\n\nWant to see how we'd grow {{company_name}}'s authority? I can share a few target sites.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Rankings + traffic for {{website}}',
     "body": "Hi there,\n\nRankings and traffic aren't separate goals — get the first right, and the second follows. And both come down to authority backlinks.\n\nWe're Uplyncio, a guest posting agency. We earn {{company_name}} quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}} that lifts your rankings and brings in organic traffic.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you just approve.\n\nMore authority, higher rankings, more of the right visitors. That's the chain reaction quality guest posting sets off.\n\nWant to see a few sites where {{company_name}} could get featured?\n\nBest,\n{{sender_name}}"},
    {"subject": "{{website}}, let's fix your backlinks",
     "body": "Hi there,\n\nIf {{company_name}}'s backlink profile is thin, outdated, or full of low-quality links, it's quietly holding back everything else you do in SEO.\n\nWe're Uplyncio, a guest posting agency that fixes exactly this. We build you a strong backlink profile through editorial guest posts on trusted, high-DA sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you just approve.\n\nA healthy backlink profile is the foundation everything else in SEO builds on. Let's get {{company_name}}'s foundation right.\n\nWant to see a few high-DA sites we could get you featured on?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'High-authority guest posts — {{website}}',
     "body": "Hi there,\n\nHigh-authority guest posts are some of the most valuable SEO assets you can own — and once earned, they keep working for {{company_name}} for years.\n\nWe're Uplyncio, a guest posting agency that specialises in them. We get you featured on trusted, high-DA sites in your niche through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built to last. We do the research, writing, and outreach — you just approve.\n\nUnlike ads that stop the moment you stop paying, quality guest posts keep driving authority and traffic long after they're published.\n\nWant to see which high-DA sites would fit {{company_name}}?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest post placements for {{website}}',
     "body": "Hi there,\n\nSecuring guest post placements on quality sites takes relationships, know-how, and time — three things most business owners don't have to spare.\n\nWe're Uplyncio, a guest posting agency that has all three. We get {{company_name}} featured on high-DA, niche-relevant sites through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you simply approve the final piece.\n\nYou focus on running your business. We'll handle the placements that grow its authority and rankings.\n\nWant to see a few sites where {{company_name}} could get featured?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Get {{website}} ranking',
     "body": "Hi there,\n\nEvery business owner wants to rank higher on Google. The ones who actually do it invest in one thing above all: quality backlinks.\n\nWe're Uplyncio, a guest posting agency that gets {{company_name}} ranking. We earn you authority links through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle everything — you just approve and watch your rankings climb.\n\nNo hype, no gimmicks, no risk. Just the kind of link building that has ranked sites for years and keeps doing it.\n\nReady to get {{company_name}} ranking? I can share a few target sites to start.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Link building agency for {{website}}',
     "body": "Hi there,\n\nDIY link building is slow, risky, and easy to get wrong — one bad batch of links can set {{company_name}} back for months.\n\nWe're Uplyncio, a link building agency that removes that risk entirely. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We find the sites, write the content, and secure the placements — you just approve.\n\nWith a specialist agency handling it, you get real results faster and with zero risk to your site.\n\nWant to see how we'd build {{company_name}}'s backlinks? I can share a few target sites.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Backlink strategy for {{website}}',
     "body": "Hi there,\n\nA smart backlink strategy isn't about chasing links — it's about earning the right ones on the right sites, consistently.\n\nWe're Uplyncio, a guest posting agency that builds exactly that strategy for {{company_name}}. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for the long term. We handle everything — you just approve.\n\nWe don't do random. We build a deliberate backlink strategy designed to grow your authority and rankings month after month.\n\nWant to see how we'd approach {{company_name}}'s strategy? I can share a few target sites.\n\nBest,\n{{sender_name}}"},
    {"subject": "{{website}}'s path to page 1",
     "body": "Hi there,\n\nPage 1 of Google isn't reserved for the biggest brands — it's earned by the sites with the strongest authority. And {{company_name}} can build that authority.\n\nWe're Uplyncio, a guest posting agency that helps you get there. We earn you quality backlinks through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you just approve.\n\nPage 1 is a matter of authority, and authority is something we build for a living.\n\nWant to see the path to page 1 for {{company_name}}? I can share a few target sites.\n\nBest regards,\n{{sender_name}}"},
    {"subject": "Guest posts that build {{website}}'s authority",
     "body": "Hi there,\n\nAuthority is the currency of search — and quality guest posts are one of the best ways to earn it for {{company_name}}.\n\nWe're Uplyncio, a guest posting agency. We build your authority through editorial guest posts on trusted, high-DA sites in your niche, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built to last. We handle the research, writing, and outreach — you just approve.\n\nMore authority means higher rankings, more traffic, and a brand that's taken seriously in your space. That's what quality guest posting builds.\n\nWant to see which high-DA sites {{company_name}} could get featured on?\n\nThanks,\n{{sender_name}}"},
    {"subject": 'SEO results for {{website}}',
     "body": "Hi there,\n\nReal SEO results don't come from tricks — they come from doing the fundamentals well, and quality backlinks are the biggest fundamental of all.\n\nWe're Uplyncio, a guest posting agency that delivers real results for brands like {{company_name}}. We earn you authority links through editorial guest posts on high-DA, niche-relevant sites, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and proven. We handle everything — you just approve and watch your rankings and traffic grow.\n\nNo hype, no shortcuts, no risk. Just the kind of link building that produces real, measurable SEO results.\n\nWant to see a few target sites for {{company_name}}?\n\nBest,\n{{sender_name}}"},
    {"subject": 'Quality links, real rankings — {{website}}',
     "body": "Hi there,\n\nQuality links and real rankings go hand in hand — you can't get the second without the first. And earning quality links is exactly what we do.\n\nWe're Uplyncio, a guest posting agency. We get {{company_name}} featured on trusted, high-DA sites through editorial guest posts, each with a natural dofollow link to {{website}} that lifts your rankings.\n\nWhite-hat, fully managed, and proven. We handle the research, writing, and outreach — you just approve.\n\nNo cheap links, no risk, no wasted budget. Just quality placements that translate directly into better rankings and more traffic.\n\nWant to see a few high-DA sites where {{company_name}} could be featured?\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Guest posting for {{website}}',
     "body": "Hi there,\n\nGuest posting, done properly, is still one of the most reliable ways to grow {{company_name}}'s rankings and authority — the catch is doing it properly.\n\nWe're Uplyncio, a guest posting agency that does. We get you featured on high-DA, niche-relevant sites through editorial guest posts, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for lasting results. We handle the research, writing, and outreach — you just approve.\n\nNo low-quality sites, no spam, no risk. Just quality guest posts that build authority and improve rankings over time.\n\nWant to see which sites {{company_name}} could get featured on?\n\nThanks,\n{{sender_name}}"},
    {"subject": "Grow {{website}}'s search presence",
     "body": "Hi there,\n\nA strong search presence isn't built overnight — it's built on quality backlinks earned consistently over time. And that's exactly what we do for {{company_name}}.\n\nWe're Uplyncio, a guest posting agency. We grow your search presence through editorial guest posts on trusted, high-DA sites in your niche, each with a natural dofollow link to {{website}}.\n\nWhite-hat, fully managed, and built for the long term. We handle the research, writing, and outreach — you just approve.\n\nConsistent quality placements compound into real, lasting authority and rankings. We make that consistency effortless for you.\n\nWant to see how we'd grow {{company_name}}'s search presence? I can share a few target sites.\n\nBest,\n{{sender_name}}"},
]


def get_template(index: int) -> dict:
    return TEMPLATES[index % len(TEMPLATES)]


def render_template(template: dict, variables: dict) -> dict:
    subject = template["subject"]
    body = template["body"]
    for key, val in variables.items():
        subject = subject.replace("{{" + key + "}}", str(val))
        body = body.replace("{{" + key + "}}", str(val))
    body_html = body.replace(chr(10), "<br>") + COMPANY_FOOTER
    return {"subject": subject, "body": body, "body_html": body_html}
