"""35 Vendor Outreach Templates — buying paid guest posts / link insertions.
Clear paid-buyer intent. 100-130 words each. "Hi there," start, first-name sign,
subject mentions site. Asks: price, TAT, dofollow/nofollow.
"""

COMPANY_FOOTER = """
<div style="margin-top:24px;font-family:Arial,sans-serif">
<div style="text-align:center;margin-bottom:12px">
<a href="{{unsubscribe_url}}" style="color:#6b7280;font-size:11px;text-decoration:underline">Unsubscribe</a>
</div>
<div style="padding-top:10px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af">
<b style="color:#1a1a2e;font-size:12px">Uplyncio.com</b><br>
<span style="color:#9ca3af">Guest Posting & Niche Edit Platform</span><br>
<a href="mailto:info@uplyncio.com" style="color:#4f46e5;text-decoration:none;font-size:11px">info@uplyncio.com</a>
</div></div>"""

VENDOR_TEMPLATES = [
    {"subject": 'Guest Post Collaboration — {{website}}',
     "body": "Hi there,\n\nI hope you're doing well. I run guest posting campaigns for a range of clients and I'm looking to place a paid guest post on {{company_name}}. Your site looks like a great fit for the kind of content I work with.\n\nBefore we proceed, could you share a few details?\n\n- Do you accept paid guest posts and link insertions?\n- Your price for each\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI have content ready to go and place orders on a regular basis, so this could turn into a steady, long-term collaboration. Looking forward to your rates.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Paid Guest Post Request — {{website}}',
     "body": "Hi there,\n\nI'd like to buy a guest post placement on {{company_name}}. I work with several clients who'd be a good match for your audience, and I'm keen to build an ongoing arrangement rather than a one-off order.\n\nCould you let me know the following?\n\n- Do you accept paid guest posts and niche edits (link insertions)?\n- Your pricing for both\n- TAT (turnaround time)\n- Are the links dofollow?\n\nI'm a regular buyer and always pay promptly, so you can count on steady orders from my side. Once I have your rates, I can send content over straight away. Thanks in advance.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post Inquiry for {{website}}',
     "body": "Hi there,\n\nI'm interested in ordering a paid guest post on {{company_name}}. I place guest posts regularly across a range of sites for my clients, and yours stood out as a strong fit.\n\nTo help me move forward quickly, could you confirm a few things?\n\n- Guest post and link insertion price\n- Turnaround time\n- Are links dofollow or nofollow?\n- Do you offer any discount on bulk orders?\n\nI'm ready to place orders as soon as I have your rates, and I'd love for this to become a regular, long-term collaboration. Looking forward to hearing back from you soon.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Paid Guest Post & Link Insertion — {{website}}',
     "body": "Hi there,\n\nI'd like to purchase guest post and link insertion placements on {{company_name}}. I manage link building for multiple clients and I'm always looking for reliable sites to work with on a repeat basis.\n\nCould you please share the details below?\n\n- Price per guest post\n- Price per link insertion (niche edit)\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI buy placements regularly and can commit to consistent volume, so a smooth first order usually leads to many more. Send me your pricing and I'll get started right away. Thanks for your time.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest Post Order — {{website}}',
     "body": "Hi there,\n\nI want to place a paid guest post order on {{company_name}}. I work with a steady roster of clients and I'm looking for quality sites to add to my regular rotation.\n\nBefore I send content, could you confirm?\n\n- Guest post rate\n- Link insertion rate\n- Turnaround time\n- Link type (dofollow or nofollow)?\n\nI'm ready to start immediately and can send repeat orders month after month, so reliable sites like yours are exactly what I'm after. Please share your rates and any bulk pricing you offer, and we can get the first order moving. Thanks.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Sponsored Post Inquiry — {{website}}',
     "body": "Hi there,\n\nI'm a guest post buyer and I'm interested in working with {{company_name}}. I handle content placements for several clients and prefer building long-term relationships with dependable site owners.\n\nCould you let me know the following?\n\n- Do you accept paid sponsored posts and link insertions?\n- Your pricing for each\n- TAT (turnaround time)\n- Are the links dofollow or nofollow?\n\nI place regular orders, pay on time, and value sites that deliver consistently. Once I have your rates I can begin sending content right away. Looking forward to your reply and hopefully a lasting collaboration.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest Posting Rates — {{website}}',
     "body": "Hi there,\n\nCould you share your guest posting rates for {{company_name}}? I run outreach for a number of clients and I'm looking to add reliable sites to my regular buying list.\n\nSpecifically, I'd like to know:\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to buy and can place orders in bulk, so if the fit is right this could be an ongoing arrangement with steady monthly volume. Please send your details and let me know if you offer any discount for repeat orders. Thanks for your time.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Paid Collaboration — {{website}}',
     "body": "Hi there,\n\nI'd like to set up a paid collaboration with {{company_name}}. I work with multiple clients on link building and I'm always looking for trustworthy sites to partner with long term.\n\nCould you please confirm the following?\n\n- Guest post and niche edit pricing\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk order rates?\n\nI buy placements regularly and pay promptly, so you can expect steady, repeat business from my side. Send over your rates and any guidelines, and I'll get the first order ready. Looking forward to working with you.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Guest Post Placement — {{website}}',
     "body": "Hi there,\n\nI'd like to buy a guest post placement on {{company_name}}. I place content across many sites for my clients and I'm keen to find reliable partners for ongoing work.\n\nCould you provide the details below?\n\n- Price for a guest post\n- Price for a link insertion\n- Turnaround time (TAT)\n- Are links dofollow or nofollow?\n\nMy content is ready on my end, so once I have your rates I can proceed immediately. I order regularly and value site owners who respond quickly and deliver on time — a good first experience usually means plenty of repeat orders. Awaiting your reply.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Link Insertion Order — {{website}}',
     "body": "Hi there,\n\nI'd like to order a link insertion (niche edit) on {{company_name}}, and possibly a guest post too. I manage placements for several clients and prefer working with the same reliable sites repeatedly.\n\nCould you please share?\n\n- Your link insertion price\n- Do you also accept paid guest posts, and at what rate?\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI place regular orders and always pay on time, so this could easily become a steady, long-term arrangement. Send me your pricing and any bulk discounts, and I'll get started. Looking forward to hearing from you soon.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Paid Guest Post Opportunity — {{website}}',
     "body": "Hi there,\n\nI'm interested in a paid guest post opportunity on {{company_name}}. I run outreach for a range of clients and I'm building a list of dependable sites for ongoing orders.\n\nCould you confirm the following for me?\n\n- Guest post and link insertion rates\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Any discounts for bulk orders?\n\nI'm ready to buy and can commit to regular volume, so reliable sites like yours are exactly what I'm looking for. Once I have your rates, I'll send content over right away and we can get things moving. Thanks for your time.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Guest Post Pricing Request — {{website}}',
     "body": "Hi there,\n\nCould you send me your guest post pricing for {{company_name}}? I handle link building for multiple clients and I'm always after quality sites to add to my regular rotation.\n\nSpecifically, I'd like to know:\n\n- Your paid guest post cost\n- Your link insertion cost\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm a regular buyer and can commit to ongoing orders with steady monthly volume, so a smooth first order usually leads to a long partnership. Please share your details and let me know if you offer bulk discounts. Looking forward to working together.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Sponsored Content Order — {{website}}',
     "body": "Hi there,\n\nI'd like to place a sponsored content order on {{company_name}}. I work with several clients and I'm looking for reliable sites to build a long-term buying relationship with.\n\nCould you please let me know?\n\n- Your sponsored post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI buy placements regularly and pay promptly, so you can expect consistent, repeat orders from me. Once I have your rates I can send content straight away and we can get the first placement live. Awaiting your details so we can move forward. Thanks.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post & Niche Edit — {{website}}',
     "body": "Hi there,\n\nI'd like to order guest posts and niche edits on {{company_name}}. I place content for multiple clients and I'm keen to work with dependable sites on a repeat basis.\n\nCould you share the following?\n\n- Price for a guest post\n- Price for a link insertion\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk pricing?\n\nI have steady volume across my clients and always pay on time, so this could become a regular, long-term collaboration. Send me your rates and guidelines, and I'll prepare the first order. Looking forward to your reply.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Paid Publishing Inquiry — {{website}}',
     "body": "Hi there,\n\nI'd like to buy paid publishing on {{company_name}}. I run outreach for a range of clients and I'm building a network of reliable sites for ongoing placements.\n\nBefore we start, could you confirm?\n\n- Do you accept paid guest posts and link insertions?\n- Your pricing for both\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to place orders now and can commit to regular volume, so a good first experience will lead to plenty more. Send me your rates and any bulk discounts you offer, and I'll get the first piece of content over to you. Thanks for your time.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest Post Buyer — {{website}}',
     "body": "Hi there,\n\nI'm a guest post buyer looking to work with {{company_name}} on a regular basis. I handle placements for several clients and prefer partnering with the same trusted sites repeatedly.\n\nCould you provide these details?\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI order consistently and always pay promptly, so you can count on steady business from my side. My content is ready, so once I have your rates I can proceed immediately. Looking forward to your reply and hopefully a long, productive collaboration.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Bulk Guest Post Inquiry — {{website}}',
     "body": "Hi there,\n\nI'd like to place bulk guest post orders on {{company_name}}. I manage link building for multiple clients and I'm looking for reliable sites that can handle steady, repeat volume.\n\nCould you please share?\n\n- Guest post rate (and any bulk discount)\n- Link insertion rate\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI have consistent volume across my clients and always pay on time, so this could be a valuable long-term arrangement for both of us. Send me your pricing and let me know how many placements you can handle per month. Looking forward to getting started.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Paid Link Placement — {{website}}',
     "body": "Hi there,\n\nI want to buy a paid link placement on {{company_name}}. I work with several clients on link building and I'm always looking for dependable sites to add to my regular rotation.\n\nCould you confirm the following?\n\n- Link insertion price\n- Guest post price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to order and can commit to steady, repeat business, so a smooth first placement usually leads to many more. Please send me your details along with any bulk discounts you offer, and we can get the first order moving right away. Thanks for your time.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Guest Post Collaboration Request — {{website}}',
     "body": "Hi there,\n\nI'd like to set up a paid guest post collaboration with {{company_name}}. I place content for multiple clients and I'm keen to build an ongoing relationship rather than a single order.\n\nCould you let me know?\n\n- Guest post and niche edit pricing\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk rates?\n\nI buy regularly and always pay promptly, so you can expect consistent orders from my side. Once I have your rates I can send content straight over and we can get the first placement live. Send me your details and let's get started.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Sponsored Guest Post — {{website}}',
     "body": "Hi there,\n\nI'm interested in a sponsored guest post on {{company_name}}. I run outreach for a range of clients and I'm building a list of trusted sites for repeat orders.\n\nCould you share the details below?\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nMy content is ready, so once I have your rates I can proceed straight away. I place orders regularly and value sites that respond quickly and deliver on time — a good first experience always leads to plenty of repeat business. Looking forward to your reply.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post Rates & TAT — {{website}}',
     "body": "Hi there,\n\nCould you send guest post rates and TAT for {{company_name}}? I handle link building for several clients and I'm looking to add reliable sites to my regular buying list.\n\nSpecifically, I'd like to know:\n\n- Your paid guest post cost\n- Your link insertion cost\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm a regular buyer with ongoing orders and steady monthly volume, so if the fit is right this could be a long partnership. Please share your details and let me know about any discounts for repeat orders. Looking forward to working together soon.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Paid Guest Article — {{website}}',
     "body": "Hi there,\n\nI want to buy a paid guest article on {{company_name}}. I place content for multiple clients and I'm always looking for quality sites to work with on a repeat basis.\n\nCould you please confirm?\n\n- Guest post and link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer discounts for repeat orders?\n\nI'm ready to proceed as soon as I have your rates, and I can commit to steady, ongoing volume. Reliable sites like yours are exactly what I'm after for long-term work. Send me your pricing and guidelines, and I'll get the first order ready. Thanks.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post Partnership — {{website}}',
     "body": "Hi there,\n\nI'd like to build a guest post partnership with {{company_name}}. I work with several clients and I'm keen to find dependable sites to collaborate with over the long term.\n\nCould you please share?\n\n- Your paid guest post and niche edit rates\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Any bulk pricing?\n\nI order consistently and always pay on time, so you can count on steady, repeat business from my side. Once I have your rates and guidelines, I can send content over right away and we can get things moving. Looking forward to a lasting collaboration.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Link Building Order — {{website}}',
     "body": "Hi there,\n\nI'm placing link building orders for my clients and I'd like to include {{company_name}} in my regular rotation. I'm always after reliable sites that deliver quality placements on time.\n\nCould you confirm the following?\n\n- Guest post price\n- Link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI buy across many sites regularly and pay promptly, so a smooth first order usually leads to steady repeat business. Please send your rates along with any bulk discounts, and I'll prepare the first placement. Looking forward to working with you on an ongoing basis. Thanks.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Guest Post Slot Inquiry — {{website}}',
     "body": "Hi there,\n\nDo you have guest post slots available on {{company_name}}? I run placements for several clients and I'm looking for reliable sites to book on a regular basis.\n\nCould you please let me know?\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to book and can commit to steady, repeat orders, so dependable sites like yours are exactly what I need. My content is ready, so once I have your rates I can proceed immediately. Send me your details and any bulk pricing, and we can get the first order confirmed.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Paid Content Placement — {{website}}',
     "body": "Hi there,\n\nI want to order paid content placement on {{company_name}}. I handle link building for multiple clients and I'm building a network of trusted sites for ongoing work.\n\nCould you please share the following?\n\n- Guest post and link insertion cost\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk discounts?\n\nI'm a serious buyer with steady monthly volume and I always pay on time, so you can expect consistent, repeat orders. Once I have your rates I can send content straight over and get the first placement live. Looking forward to your pricing and to a long-term collaboration.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post & Link Order — {{website}}',
     "body": "Hi there,\n\nI'd like to place a guest post and link order on {{company_name}}. I work with several clients and I'm keen to find dependable sites to work with repeatedly.\n\nCould you share these details?\n\n- Price per guest post\n- Price per link insertion\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to buy now and can commit to regular, ongoing volume, so a good first experience will lead to plenty more orders. Send me your rates and any bulk discounts you offer, and I'll get the first piece of content ready straight away. Looking forward to your reply.\n\nBest regards,\n{{sender_name}}"},
    {"subject": 'Sponsored Post Rates — {{website}}',
     "body": "Hi there,\n\nCould you send sponsored post rates for {{company_name}}? I run outreach for a number of clients and I'm looking to add reliable sites to my regular buying list.\n\nSpecifically, I'd like to know:\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI order regularly and always pay on time, so if the fit is right this could turn into steady, long-term business. My content is ready, so once I have your details I can proceed straight away. Please let me know your rates and any discounts for repeat orders. Thanks for your time.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Guest Post Booking — {{website}}',
     "body": "Hi there,\n\nI'd like to book a guest post on {{company_name}}. I place content for multiple clients and I prefer working with the same trusted sites again and again.\n\nCould you please confirm?\n\n- Guest post and niche edit price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk order rates?\n\nMy content is ready, so once I have your rates I can proceed immediately. I place regular orders and always pay promptly, so this could easily become a steady, long-term arrangement. Send me your pricing and guidelines, and let's get the first order started. Looking forward to it.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Paid Guest Post Collaboration — {{website}}',
     "body": "Hi there,\n\nI want a paid guest post collaboration with {{company_name}}. I handle placements for several clients and I'm building a list of dependable sites for regular, repeat orders.\n\nCould you provide these details?\n\n- Guest post price\n- Link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI buy consistently from reliable sites and always pay on time, so you can count on steady business from my side. Once I have your rates I can send content over right away and we can get the first placement live. Send me your pricing and any bulk discounts. Looking forward to working together.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Regular Guest Post Orders — {{website}}',
     "body": "Hi there,\n\nI place regular guest post orders for my clients and I'd like to add {{company_name}} to my rotation. I'm always looking for reliable sites that can handle steady, ongoing volume.\n\nCould you please share?\n\n- Your paid guest post rate\n- Your link insertion rate\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI have consistent monthly volume and always pay promptly, so you can expect repeat orders from me month after month. Send me your pricing and let me know how many placements you can handle per month, along with any bulk discounts. Looking forward to a long collaboration.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest Post Inquiry & Rates — {{website}}',
     "body": "Hi there,\n\nCould you send guest post inquiry details and rates for {{company_name}}? I handle link building for multiple clients and I'm building a network of trusted sites for ongoing orders.\n\nSpecifically, I'd like to know:\n\n- Your paid guest post cost\n- Your link insertion cost\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm ready to order regularly and always pay on time, so if the fit is right this could become a steady partnership with consistent monthly volume. My content is ready, so once I have your rates I can proceed straight away. Thanks for your time and I look forward to your reply.\n\nThanks,\n{{sender_name}}"},
    {"subject": 'Paid Niche Edit Request — {{website}}',
     "body": "Hi there,\n\nI'd like to order a paid niche edit (link insertion) on {{company_name}}, and possibly guest posts as well. I manage link building for several clients and prefer working with dependable sites repeatedly.\n\nCould you please confirm?\n\n- Your link insertion price\n- Do you also offer paid guest posts, and at what rate?\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI'm a regular buyer with steady volume and always pay promptly, so this could become a long-term arrangement. Send me your rates and any bulk discounts, and I'll get the first order ready. Looking forward to hearing back from you soon.\n\nBest,\n{{sender_name}}"},
    {"subject": 'Guest Post Deal — {{website}}',
     "body": "Hi there,\n\nI'd like to close a guest post deal with {{company_name}}. I work with a steady roster of clients and I'm looking for reliable sites to partner with on a long-term basis.\n\nCould you share the following?\n\n- Guest post and link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n- Do you offer bulk discounts?\n\nI'm ready to buy and can commit to consistent, repeat orders, so a smooth first placement usually leads to many more. My content is ready, so once I have your rates we can finalize quickly. Send me your details and let's get the first order moving. Thanks.\n\nRegards,\n{{sender_name}}"},
    {"subject": 'Guest Posting Collaboration — {{website}}',
     "body": "Hi there,\n\nI'm looking for a guest posting collaboration with {{company_name}}. I place content for multiple clients and I value building lasting relationships with trusted site owners.\n\nCould you please let me know?\n\n- Your paid guest post price\n- Your link insertion price\n- Turnaround time (TAT)\n- Are the links dofollow or nofollow?\n\nI buy regularly, pay promptly, and prefer working with the same reliable partners again and again. Once I have your rates and guidelines I can send content over straight away and we can get the first placement live. Send me your details and any bulk pricing, and let's get started. Looking forward to it.\n\nBest,\n{{sender_name}}"},
]


def get_vendor_template(index: int) -> dict:
    return VENDOR_TEMPLATES[index % len(VENDOR_TEMPLATES)]


def render_vendor_template(template: dict, variables: dict) -> dict:
    subject = template["subject"]
    body = template["body"]
    for key, val in variables.items():
        subject = subject.replace("{{" + key + "}}", str(val))
        body = body.replace("{{" + key + "}}", str(val))
    body_html = body.replace(chr(10), "<br>") + COMPANY_FOOTER
    return {"subject": subject, "body": body, "body_html": body_html}
